// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackStack() {
  return window['go']['main']['App']['GetBackStack']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2, arg3);
}

export function LoadRoot() {
  return window['go']['main']['App']['LoadRoot']();
}

export function UpdateWorkingDirectory(arg1) {
  return window['go']['main']['App']['UpdateWorkingDirectory'](arg1);
}

export function WorkingDirectory() {
  return window['go']['main']['App']['WorkingDirectory']();
}
