// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.Item>>;

export function WorkingDirectory():Promise<any>;
