// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBackStack():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.Item>>;

export function UpdateWorkingDirectory(arg1:main.WorkingDirectoryEvent):Promise<void>;

export function WorkingDirectory():Promise<any>;
